Repository Mjolnir-MD/Mjolnir, pull requests merged in 2019-10, with the labels that each got.

#164 Refactor reading table provided by other files
  mjolnir/input/read_forcefield.hpp
  mjolnir/input/read_input_file.hpp
  mjolnir/input/read_simulator.cpp
  mjolnir/input/read_simulator.hpp
  mjolnir/input/read_system.hpp
  mjolnir/input/read_table_from_file.cpp
  mjolnir/input/read_table_from_file.hpp
  mjolnir/input/read_units.cpp
  mjolnir/input/read_units.hpp
  test/core/test_read_molecular_dynamics_simulator.cpp
  test/core/test_read_simulated_annealing_simulator.cpp
  test/core/test_read_steepest_descent_simulator.cpp
  test/core/test_read_switching_forcefield_simulator.cpp
  test/core/test_read_unit.cpp
Labels: P-HIGH, refactoring

#165 fix openmp implementations of cell lists
  .travis.yml
  mjolnir/omp/PeriodicGridCellList.hpp
  mjolnir/omp/UnlimitedGridCellList.hpp
  mjolnir/omp/sort.hpp
  mjolnir/util/logger.hpp
Labels: P-HIGH, bug

#160 Uniform potential
  mjolnir/input/read_local_interaction.hpp
  mjolnir/input/read_local_potential.hpp
  mjolnir/potential/local/UniformPotential.hpp
  test/core/CMakeLists.txt
  test/core/test_read_uniform_potential.cpp
Labels: enhancement

#168 split participants into two, left and right sides in the pair list
  mjolnir/core/NaivePairCalculation.hpp
  mjolnir/core/NeighborList.hpp
  mjolnir/core/PeriodicGridCellList.hpp
  mjolnir/core/UnlimitedGridCellList.hpp
  mjolnir/core/VerletList.hpp
  mjolnir/forcefield/3SPN2/ThreeSPN2BaseBaseInteraction.hpp
  mjolnir/forcefield/3SPN2/ThreeSPN2BaseBaseInteractionPotential.hpp
  mjolnir/forcefield/3SPN2/ThreeSPN2ExcludedVolumePotential.hpp
  mjolnir/interaction/global/GlobalPairExcludedVolumeInteraction.hpp
  mjolnir/interaction/global/GlobalPairInteraction.hpp
  mjolnir/interaction/global/GlobalPairLennardJonesInteraction.hpp
  mjolnir/interaction/global/GlobalPairUniformLennardJonesInteraction.hpp
  mjolnir/omp/GlobalPairExcludedVolumeInteraction.hpp
  mjolnir/omp/GlobalPairInteraction.hpp
  mjolnir/omp/GlobalPairLennardJonesInteraction.hpp
  mjolnir/omp/GlobalPairUniformLennardJonesInteraction.hpp
  mjolnir/omp/ThreeSPN2BaseBaseInteraction.hpp
  mjolnir/potential/global/DebyeHuckelPotential.hpp
  mjolnir/potential/global/ExcludedVolumePotential.hpp
  mjolnir/potential/global/HardCoreExcludedVolumePotential.hpp
  mjolnir/potential/global/LennardJonesPotential.hpp
  mjolnir/potential/global/UniformLennardJonesPotential.hpp
  test/core/test_3spn2_base_base_interaction_potential.cpp
  test/core/test_periodic_cell_list.cpp
  test/core/test_periodic_verlet_list.cpp
  test/core/test_unlimited_cell_list.cpp
  test/core/test_unlimited_verlet_list.cpp
  test/omp/test_omp_global_uniform_lennard_jones_interaction.cpp
Labels: P-MID, enhancement

#161 add protein-DNA nonspecific interaction
  book/ja/SUMMARY.md
  book/ja/refs/GlobalForceField.md
  book/ja/refs/ProteinDNANonSpecificInteraction.md
  mjolnir/forcefield/CMakeLists.txt
  mjolnir/forcefield/PDNS/CMakeLists.txt
  mjolnir/forcefield/PDNS/ProteinDNANonSpecificInteraction.cpp
  mjolnir/forcefield/PDNS/ProteinDNANonSpecificInteraction.hpp
  mjolnir/forcefield/PDNS/ProteinDNANonSpecificPotential.cpp
  mjolnir/forcefield/PDNS/ProteinDNANonSpecificPotential.hpp
  mjolnir/input/read_global_interaction.hpp
  mjolnir/input/read_local_interaction.hpp
  mjolnir/omp/CMakeLists.txt
  mjolnir/omp/ProteinDNANonSpecificInteraction.cpp
  mjolnir/omp/ProteinDNANonSpecificInteraction.hpp
  mjolnir/omp/omp.hpp
  test/core/CMakeLists.txt
  test/core/test_pdns_interaction.cpp
  test/core/test_pdns_potential.cpp
  test/core/test_read_3spn2_base_base_interaction.cpp
  test/core/test_read_pdns_interaction.cpp
  test/omp/CMakeLists.txt
  test/omp/test_omp_global_pdns_interaction.cpp
Labels: enhancement

#174 refactor: math vector related stuffs and AxisAlignedPlane
  mjolnir/core/AxisAlignedPlane.hpp
  mjolnir/input/read_external_interaction.hpp
  mjolnir/input/read_system.hpp
  mjolnir/omp/sort.hpp
  test/core/test_axis_aligned_plane_shape.cpp
  test/core/test_read_external_forcefield.cpp
  test/integration/test_BAOABIntegrator/test_BAOABIntegrator.cpp
  test/omp/test_omp_external_distance_interaction.cpp
Labels: refactoring

#171 PWMcos forcefield
  mjolnir/forcefield/CMakeLists.txt
  mjolnir/forcefield/PWMcos/CMakeLists.txt
  mjolnir/forcefield/PWMcos/PWMcosInteraction.cpp
  mjolnir/forcefield/PWMcos/PWMcosInteraction.hpp
  mjolnir/forcefield/PWMcos/PWMcosPotential.cpp
  mjolnir/forcefield/PWMcos/PWMcosPotential.hpp
  mjolnir/input/read_global_interaction.hpp
  mjolnir/omp/CMakeLists.txt
  mjolnir/omp/PWMcosInteraction.cpp
  mjolnir/omp/PWMcosInteraction.hpp
  mjolnir/omp/omp.hpp
  test/core/CMakeLists.txt
  test/core/test_pwmcos_interaction.cpp
  test/core/test_pwmcos_potential.cpp
  test/core/test_read_pwmcos_interaction.cpp
  test/omp/CMakeLists.txt
  test/omp/test_omp_global_pwmcos_interaction.cpp
Labels: P-HIGH, enhancement
